CREATE TABLE IF NOT EXISTS STORE (
    `KEY` VARCHAR(255) NOT NULL,
    `VALUE` VARCHAR(255) NOT NULL,
    `EXPIRATION_TS` TIMESTAMP NOT NULL,
    PRIMARY KEY (`KEY`),
    INDEX idx_expiration_ts (`EXPIRATION_TS`)
);